Site/Main_site/Sample_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from .views import home_page
from products.views import ProductListPage, ProductDetailPage, ProductDetailSlugView
from checkout.views import checkout_page
from shoppingcart.views import cart_home

from products.views import ProductListPage


urlpatterns = [
    url(r'^$', ProductListPage),
    url(r'^cart/', include(("shoppingcart.urls", "cart"), namespace="cart")),
    url(r'^checkout/', checkout_page),
    url(r'^products/$', ProductListPage),
    url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
    path('admin/', admin.site.urls)]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL,
    document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

Site/Main_site/shoppingcart/urls.py
from django.conf.urls import include, url

from .views import(
    cart_home,
    cart_update
)

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^update/$', cart_update, name='update')
]

Site/Main_site/checkout/models.py
from django.db import models

# Create your models here.

Site/Main_site/products/models.py
from django.db import models
from django.db.models.signals import pre_save
import os, random
from .utils import unique_slug_generator


class ProductManager(models.Manager):
    def get_by_id(self, id):
        return self.get_queryset().filter(id=id)

   
def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext

def upload_image_path(instance, filename):
    new_filename = random.randint(1, 9000000)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "products/{new_filename}/{final_filename}".format(
        new_filename=new_filename,
        final_filename=final_filename
        )

class Product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=20, default=99.99)
    image = models.ImageField(upload_to=upload_image_path, null=False, blank=False)
    slug = models.SlugField(blank=True, default="", unique=True, editable=False)
    qauntity = models.IntegerField(blank=False, default=1)
    height = models.IntegerField(blank=True, default=1)
    length = models.IntegerField(blank=True, default=1)

    objects = ProductManager()

    def get_url(self):
        return"/products/{slug}/".format(slug=self.slug)

    def __str__(self):
        return self.title


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver, sender=Product)
# Create your models here.

Site/Main_site/shoppingcart/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_save, post_save, m2m_changed
from products.models import Product as Product


User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        request.session.set_expiry(300)
        qs = Cart.objects.filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            print('Cart ID exists', cart_id)
            cart_obj = qs.first()
        else:
            cart_obj = Cart.objects.new_cart(user=None)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new_cart(self, user=None):
        return self.model.objects.create(user=user)



class Cart(models.Model):
    user = models.ForeignKey(
        User, null=True, blank=True, on_delete=models.SET_NULL)
    products = models.ManyToManyField(Product, blank=True)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    subtotal = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CartManager()


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()


m2m_changed.connect(m2m_changed_cart_receiver, sender= Cart.products.through)

def pre_save_cart_reciever(sender, instance, *arg, **kwargs):
    if instance.subtotal > 0:
        instance.total = instance.subtotal + 10
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_reciever, sender=Cart)

Site/Main_site/Sample_site/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse
from django.template import RequestContext

def home_page(request):
    return render(request, "home_page.html",{})



def handler404(request, exception, template_name="404.html"):
    response = render_to_response("404.html")
    return response

Site/Main_site/checkout/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse
from django.template import RequestContext

def checkout_page(request):
    return render(request, "checkout_page.html",{})

Site/Main_site/products/views.py
from django.shortcuts import render, get_object_or_404
from shoppingcart.models import Cart
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from django.http import Http404
from urllib import request


from .models import Product

def ProductListPage(request):
    queryset = Product.objects.all()
    context = {
        'object_list' : queryset
    }
    return render(request, "product_list.html", context)

class ProductDetailPage(DetailView):
    template_name = "product_detail.html"
    queryset = Product.objects.all()


class ProductDetailSlugView(DetailView):
    template_name = "product_detail.html"
    queryset = Product.objects.all()

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        try:
            instance = Product.objects.get(slug=slug)
        except Product.DoesNotExist:
            raise Http404("Not Found")
        except Product.MultipleObjectsReturned:
            queryset = Product.objects.filter(slug=slug, active=True)
            instance = queryset.first()
        except:
            raise Http404("???")
        return instance

    def get_context(self, *args, **kwargs):
        context = super().get_context(self, *args,**kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context
    
    


# Create your views here.

Site/Main_site/shoppingcart/views.py
from django.shortcuts import render, redirect
from .models import Cart
from django.shortcuts import get_object_or_404
from products.models import Product as Product


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, 'cart_page.html', {"cart": cart_obj})


def cart_update(request):
    product_id = request.POST.get('product_id')
    if product_id is not None:
        product_obj = Product.objects.get(id=product_id)
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
        else:
            cart_obj.products.add(product_obj)
            cart_obj.products.quantity=-1
        print(product_obj)
    return redirect("cart:home")
   
    

# Create your views here.

Site/Main_site/templates/cart_page.html
{% extends 'home_page.html' %}
{% block content %}

<!doctype html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap core CSS -->

</head>

<body class="bg-light">
  {% if cart.products.exists %}
  <div class="container">
    <table id="cart" class="table table-hover table-condensed">
      <thead>
        <tr>
          <th style="width:100%">Product</th>
          <th style="width:1%">Price</th>
        </tr>
      </thead>





      {% for product in cart.products.all %}
      <tbody>
        <tr>
          <td data-th="Product">
            <div class="row">
              <div class="col-sm-2 hidden-xs"><img src="{{ product.image.url }}" alt="..." class="img-fluid" /></div>
              <div class="col-sm-10">
                <h4 class="nomargin">{{ product.title }}</h4>
                <p>{{ product.description }}.</p>
              </div>
            </div>
          </td>
          <td data-th="Price">${{ product.price }}</td>
          <td class="actions" data-th="">
            {% include 'snippets/cartbuttons.html' with cart=cart incart=True %}
          </td>
        </tr>
      </tbody>







      {% endfor %}
      <tfoot>
        <tr>
          <td><a href="/" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
          <td colspan="2" class="hidden-xs"></td>
          <td class="hidden-xs text-center"><strong>Total ${{ cart.total }}</strong></td>
          <td><a href="/checkout/" class="btn btn-success btn-block" data-toggle="modal" data-target="#exampleModal"
              data-whatever="@getbootstrap">Checkout <i class="fa fa-angle-right"></i></a></td>
        </tr>
      </tfoot>
    </table>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Checkout</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form>
              <div class="form-group">
                <label for="name" class="col-form-label">Contact Info:</label>
                <input type="text" class="form-control" id="name" placeholder="Email">
              </div>
              <div class="input-group">
                <input type="text" class="form-control" placeholder="First Name" />
                <span class="input-group-addon"> </span>
                <input type="text" class="form-control" placeholder="Last Name" />
              </div>
              <br>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Street Address">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="City">
              </div>
              <div class="d-flex justify-content-center">
                <input type="text" class="form-control col-sm-3" placeholder="Country" />
                <input type="text" class="form-control col-sm-3" placeholder="State/Region" />
                <input type="text" class="form-control col-sm-3" placeholder="Zip" />
              </div>
            </form>
            </form>
          </div>
          <div class="modal-footer">
            <td class="hidden-xs text-center"><strong>Total ${{ cart.total }}</strong></td>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Checkout</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

</html>
{% else %}
<div class="d-flex justify-content-center" style="margin-top: 5%;">
  <div class="jumbotron my-auto">
    <h1 class="font-weight-light"> Your cart is currently empty... </h1>
    <div class="d-flex justify-content-center" >
    <a href="/" class="btn btn-primary"><i class="fa fa-angle-left"></i> Continue Shopping</a>
    </div>
    </div>
</div>
</body>

</html>

{% endif %}

{% endblock content %}

Site/Main_site/templates/checkout_page.html
{% extends 'home_page.html' %}
{% block content %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap core CSS -->

</head>

<body class="bg-light">
  {% if cart.products.exists %}
  <div class="container">
      <table id="cart" class="table table-hover table-condensed">
                <thead>
                <tr>
                  <th style="width:100%">Product</th>
                  <th style="width:1%">Price</th>
                </tr>
              </thead>
              

    
    
    
  {% for product in cart.products.all %}
  <tbody>
      <tr>
        <td data-th="Product">
          <div class="row">
            <div class="col-sm-2 hidden-xs"><img src="{{ product.image.url }}"  alt="..." class="img-fluid"/></div>
            <div class="col-sm-10">
              <h4 class="nomargin">{{ product.title }}</h4>
              <p>{{ product.description }}.</p>
            </div>
          </div>
        </td>
        <td data-th="Price">${{ product.price }}</td>
        <td class="actions" data-th="">
            {% include 'snippets/cartbuttons.html' with cart=cart incart=True %}								
        </td>
      </tr>
    </tbody>
  

  
  
  


  {% endfor %}
  <tfoot>
      <tr>
        <td><a href="/" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
        <td colspan="2" class="hidden-xs"></td>
        <td class="hidden-xs text-center"><strong>Total ${{ cart.total }}</strong></td>
        <td><a href="#" class="btn btn-success btn-block">Checkout <i class="fa fa-angle-right"></i></a></td>
      </tr>
    </tfoot>
  </table>
  </div>
</body>
</html>
  {% else %}
  <div class="row">
    <div class="jumbotron-fluid">
      {% load static %}
      <img src="{% static 'img/emptycart.jpg' %}" style="width:80vw; height: 60vh;">
    </div>
  </div>
</body>

</html>

{% endif %}

{% endblock content %}

Site/Main_site/templates/home_page.html
<html lang="en">

<head>
  <title>SITE NAME</title> <!---Site Name--->
  <meta charset="utf-8" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% load static %}


<link rel="stylesheet" href="{% static 'css/welcome_page.css' %}">
</head>

<body style="background-color: grey; height:100%; position: relative;">
<div class="big_container">
  <!--- JS --->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <!---<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

  <!--- Nav --->
  <nav class="navbar navbar-dark static-top" style="background-color: rgb(33,32,33)">
  <div class="container">
    <a class="navbar-brand" href="/">
      {% load static %}
      <img src="{% static 'img/logo.png' %}" class="img-fluid" style="max-width: 25%; min-width: 25%; margin-left: 2vw;">
    </a>
    <!--- <img src="{% static 'assets/images/b.jpg' %}" class="img-fluid" style="max-width: 25%; min-width: 25%;"> -->
    </a>
    <ul class="navbar-nav ml-auto">
      <div class="float-top">
        <a class="nav-link" href="/cart"><i class="fa fa-shopping-cart" style="font-size:24px; color: white"></i></a>
      </div>
    </ul>
    </div>
  </nav>

  <!--- Site Content --->
  <div style="height:5%;"></div>

  <div class="container">
    {% block content %}{% endblock %}

  </div>



<!-- Footer -->
<footer class="page-footer font-small mt-2 pt-4 static-bottom"
  style="background-color: rgb(33,32,33); position: absolute;
  bottom: 0;
  width: 100%;">

  <!-- Footer Elements -->
  <div class="container">

    <!-- Social buttons -->
    <ul class="list-unstyled list-inline text-center">
      <li class="list-inline-item">
        <a class="btn-floating btn-fb mx-1">
          <i class="fa fa-facebook" style="font-size:24px; color: white" href=""> </i>
        </a>
        <a class="btn-floating btn-fb mx-1" href="https://www.instagram.com">
          <i class="fa  fa-instagram" style="font-size:24px; color: white"> </i>
        </a>
      </li>
    </ul>
    <!-- Social buttons -->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="container" style="height: 2%;"></div>
  <!-- Copyright -->

</footer>

</div>

</body>
</div>
</html>

Site/Main_site/templates/product_detail.html
{% extends 'home_page.html' %}
{% block content %}



<!DOCTYPE html>
<html lang="en">

<head>

        <title>Cartoon Glass Work</title>
        <meta charset="utf-8" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
                integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
                crossorigin="anonymous">
        <link rel="stylesheet"
                href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
        <div class="shadow p-3 mb-5 bg-white rounded" style="min-height: 50vh;">

                <!--Main layout-->
                <main class="mt-1 pt-2">
                        <div class="container dark-grey-text mt-5">

                                <!--Grid row-->
                                <div class="row wow fadeIn">

                                        <!--Grid column-->
                                        <div class="col-md-12 mb-6">

                                                <img src="{{ object.image.url }}"
                                                        class="img-fluid" style="min-width:60vw; max-height:70vh;">

                                        </div>
                                        <!--Grid column-->

                                        <!--Grid column-->
                                        <div class="col-md-6 mb-6">

                                                <!--Content-->
                                                <div class="p-4">

                                                        <p class="lead">
                                                                <p class="lead font-weight-bold">{{ object.title }}</p>

                                                        </p>
                                                        <br></br>
                                                        <span>${{ object.price }}</span>
                                                        <td>{% include 'snippets/cartbuttons.html' with product=object cart=cart%}
                                                        </td>


                                                        <br></br>
                                                        <hr class="my-2"></hr>
                                                        <p class="lead"> Description..</p>
                                                        <p>{{ object.description }}</p>
                                                        <p class="lead"> Height: {{ object.height}} </p>
                                                        <p class="lead"> Length: {{ object.length }} </p>




                                                        <!-- Default input -->




                                                </div>
                                                <!--Content-->

                                        </div>
                                        <!--Grid column-->

                                </div>
                                <!--Grid row-->

                                <hr>

                                <!--Grid row-->
                                <div class="row d-flex justify-content-center wow fadeIn">


                                </div>
                </main>
        </div>
        <!--Main layout-->
</body>

</html>
{% endblock  %}

Site/Main_site/templates/product_list.html
{% extends "home_page.html" %}
{% block content %}


<html lang="en">

<head>
    <title>Cartoon Glass Work</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% load static %}


<link rel="stylesheet" href="{% static 'css/welcome_page.css' %}">
</head>


<!--- Site Content --->

<div class="shadow p-3 bg-white rounded" style="min-height: 100vh;">
    <!-- Possibly move outside container? -->
    {% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a></li>
        {% endif %}

        {% for page_num in page_obj.paginator.page_range %}
        <li class="page-item"><a class="page-link" href="?page={{ page_num }}">
                {{ page_num }}
            </a></li>
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
    {% endif %}
    <div class="row">
    {% if object_list.exists %}
        {% for obj in object_list %}

        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-3 ">

                <a href="{{ obj.get_url }}">
                    <p class="price">${{ obj.price }}</p>
                    <img class="img-thumbnail" style="width:35vw; height:30vh;" src="{{ obj.image.url }}">
                    <h3 class="title">{{ obj.title }}</h3>
                </a>

        </div>
        {% endfor %}
    </div>
    
</div>
{% else %}
<div class="container">
<div class="d-flex justify-content-center" style="margin-top: 25%;">
  <div class="jumbotron my-auto">
    <h1 class="font-weight-light"> Hmm... seems like theres no products right now. </h1>
    <div class="d-flex justify-content-center" >
    <p1 class="font-weight-light"> Check back later for awesome deals.</p1>
    </div>
{% endif %}
{% endblock %}

Site/Main_site/templates/snippets/cartbuttons.html
<form method='POST' action='{% url "cart:update" %}' class="form"> {% csrf_token %}
        <input type="hidden" name="product_id" value="{{ product.id }}" />
        {% if product in Cart.products.all or incart %}
        <button type="submit" class="btn btn-danger btn-md my-0 p btn-sm" type="submit">
                <i class="fa fa-trash-o"></i>
        </button>
        {% elif product.qauntity < 1 %}
        <h1>SOLD OUT</h1>
        {% else %}
        <button type="submit" class="btn btn-primary btn-md my-0 p" type="submit">Add
                to cart
                <i class="fa fa-shopping-cart"></i>

        </button>
        {% endif %}


</form>